## Hospital Readmission Analysis

#### Load and inspect the data using Python

In [1]:
# Import Pandas and read CSV files

import pandas as pd

df = pd.read_csv('C:/Users/Habibur/Diabetes 130-US Hospitals for Years 1999-2008/diabetic_data.csv')
mapping = pd.read_csv('C:/Users/Habibur/Diabetes 130-US Hospitals for Years 1999-2008/IDS_mapping.csv')

In [2]:
# To identify how many rows and columns

df.shape

(101766, 50)

In [3]:
# To show top 5 rows

df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [4]:
# To show bottom 5 rows

df.tail()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
101761,443847548,100162476,AfricanAmerican,Male,[70-80),?,1,3,7,3,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101762,443847782,74694222,AfricanAmerican,Female,[80-90),?,1,4,5,5,...,No,Steady,No,No,No,No,No,No,Yes,NO
101763,443854148,41088789,Caucasian,Male,[70-80),?,1,1,7,1,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101764,443857166,31693671,Caucasian,Female,[80-90),?,2,3,7,10,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101765,443867222,175429310,Caucasian,Male,[70-80),?,1,1,7,6,...,No,No,No,No,No,No,No,No,No,NO

In [5]:
# Shows important structural information about the dataset

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  str
 3   gender                    101766 non-null  str
 4   age                       101766 non-null  str
 5   weight                    101766 non-null  str
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  str
 11  medical_specialty         101766 non-null  str
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  str
 19  diag_2                    101766 non-null  str
 20  diag_3                    101766 non-null  str
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    str
 23  A1Cresult                 17018 non-null   str
 24  metformin                 101766 non-null  str
 25  repaglinide               101766 non-null  str
 26  nateglinide               101766 non-null  str
 27  chlorpropamide            101766 non-null  str
 28  glimepiride               101766 non-null  str
 29  acetohexamide             101766 non-null  str
 30  glipizide                 101766 non-null  str
 31  glyburide                 101766 non-null  str
 32  tolbutamide               101766 non-null  str
 33  pioglitazone              101766 non-null  str
 34  rosiglitazone             101766 non-null  str
 35  acarbose                  101766 non-null  str
 36  miglitol                  101766 non-null  str
 37  troglitazone              101766 non-null  str
 38  tolazamide                101766 non-null  str
 39  examide                   101766 non-null  str
 40  citoglipton               101766 non-null  str
 41  insulin                   101766 non-null  str
 42  glyburide-metformin       101766 non-null  str
 43  glipizide-metformin       101766 non-null  str
 44  glimepiride-pioglitazone  101766 non-null  str
 45  metformin-rosiglitazone   101766 non-null  str
 46  metformin-pioglitazone    101766 non-null  str
 47  change                    101766 non-null  str
 48  diabetesMed               101766 non-null  str
 49  readmitted                101766 non-null  str
dtypes: int64(13), str(37)
memory usage: 38.8 MB

In [6]:
# Provides statistical summaries of numerical columns

df.describe(include='all')

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
count,1.017660e+05,1.017660e+05,101766,101766,101766,101766,101766.000000,101766.000000,101766.000000,101766.000000,...,101766,101766,101766,101766,101766,101766,101766,101766,101766,101766
unique,NaN,NaN,6,3,10,10,NaN,NaN,NaN,NaN,...,1,4,4,2,2,2,2,2,2,3
top,NaN,NaN,Caucasian,Female,[70-80),?,NaN,NaN,NaN,NaN,...,No,No,No,No,No,No,No,No,Yes,NO
freq,NaN,NaN,76099,54708,26068,98569,NaN,NaN,NaN,NaN,...,101766,47383,101060,101753,101765,101764,101765,54755,78363,54864
mean,1.652016e+08,5.433040e+07,NaN,NaN,NaN,NaN,2.024006,3.715642,5.754437,4.395987,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1.026403e+08,3.869636e+07,NaN,NaN,NaN,NaN,1.445403,5.280166,4.064081,2.985108,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.252200e+04,1.350000e+02,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,8.496119e+07,2.341322e+07,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,2.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1.523890e+08,4.550514e+07,NaN,NaN,NaN,NaN,1.000000,1.000000,7.000000,4.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2.302709e+08,8.754595e+07,NaN,NaN,NaN,NaN,3.000000,4.000000,7.000000,6.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,4.438672e+08,1.895026e+08,NaN,NaN,NaN,NaN,8.000000,28.000000,25.000000,14.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Define the unit of analysis

In [7]:
len(df)

101766

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df['patient_nbr'].nunique()

71518

#### Clean missing and invalid values

In [10]:
# Convert question marks into missing values

df = df.replace('?', pd.NA)

In [11]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [12]:
# Check missing values

df.isnull().sum().sort_values(ascending=False).head(10)

weight               98569
max_glu_serum        96420
A1Cresult            84748
medical_specialty    49949
payer_code           40256
race                  2273
diag_3                1423
diag_2                 358
diag_1                  21
patient_nbr              0
dtype: int64

In [13]:
# Check readmission categories

df['readmitted'].value_counts(dropna=False)

readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

#### Check data quality

In [14]:
df['age'].value_counts(dropna=False)

age
[70-80)     26068
[60-70)     22483
[50-60)     17256
[80-90)     17197
[40-50)      9685
[30-40)      3775
[90-100)     2793
[20-30)      1657
[10-20)       691
[0-10)        161
Name: count, dtype: int64

In [15]:
df['gender'].value_counts(dropna=False)

gender
Female             54708
Male               47055
Unknown/Invalid        3
Name: count, dtype: int64

In [16]:
df['time_in_hospital'].describe()

count    101766.000000
mean          4.395987
std           2.985108
min           1.000000
25%           2.000000
50%           4.000000
75%           6.000000
max          14.000000
Name: time_in_hospital, dtype: float64

In [17]:
df['number_inpatient'].describe()

count    101766.000000
mean          0.635566
std           1.262863
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max          21.000000
Name: number_inpatient, dtype: float64

In [18]:
df.columns.tolist()

['encounter_id',
 'patient_nbr',
 'race',
 'gender',
 'age',
 'weight',
 'admission_type_id',
 'discharge_disposition_id',
 'admission_source_id',
 'time_in_hospital',
 'payer_code',
 'medical_specialty',
 'num_lab_procedures',
 'num_procedures',
 'num_medications',
 'number_outpatient',
 'number_emergency',
 'number_inpatient',
 'diag_1',
 'diag_2',
 'diag_3',
 'number_diagnoses',
 'max_glu_serum',
 'A1Cresult',
 'metformin',
 'repaglinide',
 'nateglinide',
 'chlorpropamide',
 'glimepiride',
 'acetohexamide',
 'glipizide',
 'glyburide',
 'tolbutamide',
 'pioglitazone',
 'rosiglitazone',
 'acarbose',
 'miglitol',
 'troglitazone',
 'tolazamide',
 'examide',
 'citoglipton',
 'insulin',
 'glyburide-metformin',
 'glipizide-metformin',
 'glimepiride-pioglitazone',
 'metformin-rosiglitazone',
 'metformin-pioglitazone',
 'change',
 'diabetesMed',
 'readmitted']

#### Create analysis-ready columns

In [19]:
# To check readmission within 30 days, create a new column 'readmitted_30_days'

df['readmitted_30_days'] = (df['readmitted'] == '<30').astype('int')
df[['readmitted', 'readmitted_30_days']].value_counts(dropna=False)

readmitted  readmitted_30_days
NO          0                     54864
>30         0                     35545
<30         1                     11357
Name: count, dtype: int64

In [20]:
# Calculate the percentage of readmission within 30 days

readmission_rate = (
    df['readmitted_30_days'].mean() * 100
)
print(f'Recorded <30 rate: {readmission_rate:.2f}%')

Recorded <30 rate: 11.16%

##### Identify patient groups with higher readmission rates

In [21]:
# To check which age groups have higher recorded 30-day readmission rates

age_analysis = (
    df.groupby('age', observed=True)
      ['readmitted_30_days']
      .agg(['mean', 'count'])
      .reset_index()
)

age_analysis['readmission_rate_pct'] = (
    age_analysis['mean'] * 100
)

age_analysis

        age      mean  count  readmission_rate_pct
0    [0-10)  0.018634    161              1.863354
1   [10-20)  0.057887    691              5.788712
2   [20-30)  0.142426   1657             14.242607
3   [30-40)  0.112318   3775             11.231788
4   [40-50)  0.106040   9685             10.604027
5   [50-60)  0.096662  17256              9.666203
6   [60-70)  0.111284  22483             11.128408
7   [70-80)  0.117731  26068             11.773055
8   [80-90)  0.120835  17197             12.083503
9  [90-100)  0.110992   2793             11.099177

In [22]:
gender_analysis = (
    df.groupby('gender')['readmitted_30_days']
      .agg(['count', 'mean'])
      .reset_index()
)

gender_analysis['readmission_rate_pct'] = (
    gender_analysis['mean'] * 100
)

gender_analysis

            gender  count      mean  readmission_rate_pct
0           Female  54708  0.112452             11.245156
1             Male  47055  0.110615             11.061524
2  Unknown/Invalid      3  0.000000              0.000000

In [23]:
# Calculate the recorded 30-day readmission rate for each group

inpatient_analysis = (
    df.groupby('number_inpatient', observed=False)
      .agg(
          Total_Encounters=('readmitted_30_days', 'count'),
          Readmission_Rate=('readmitted_30_days', 'mean')
      )
      .reset_index()
)

inpatient_analysis['Readmission_Rate'] *= 100

inpatient_analysis.round(2)

    number_inpatient  Total_Encounters  Readmission_Rate
0                  0             67630              8.44
1                  1             19521             12.92
2                  2              7566             17.43
3                  3              3411             20.29
4                  4              1622             23.61
5                  5               812             31.40
6                  6               480             34.58
7                  7               268             35.45
8                  8               151             44.37
9                  9               111             42.34
10                10                61             42.62
11                11                49             67.35
12                12                34             50.00
13                13                20             50.00
14                14                10             40.00
15                15                 9            100.00
16                16                 6             33.33
17                17                 1            100.00
18                18                 1              0.00
19                19                 2             50.00
20                21                 1            100.00

In [24]:
# To check the diabetes medication

df['medication_changed'] = (df['change'].map({'Ch': 1, 'No': 0})).astype('Int64')

df[['change', 'medication_changed']].value_counts()

change  medication_changed
No      0                     54755
Ch      1                     47011
Name: count, dtype: int64

##### Investigate clinical and admission factors

In [25]:
# To check whether 30-day readmission varies with the length of the hospital stay

df['length_of_stay_group'] = pd.cut(
    df['time_in_hospital'],
    bins=[0, 3, 7, 14],
    labels=['1-3 days', '4-7 days', '8-14 days']
)

df['length_of_stay_group'].value_counts()

length_of_stay_group
1-3 days     49188
4-7 days     37288
8-14 days    15290
Name: count, dtype: int64

In [26]:
df['prior_inpatient_group'] = pd.cut(
    df['number_inpatient'],
    bins=[-1, 0, 1, float('inf')],
    labels=['0 visits', '1 visit', '2+ visits']
)

df['prior_inpatient_group'].value_counts()

prior_inpatient_group
0 visits     67630
1 visit      19521
2+ visits    14615
Name: count, dtype: int64

In [27]:

df['prior_emergency_group'] = pd.cut(
    df['number_emergency'],
    bins=[-1, 0, 1, float('inf')],
    labels=['0 visits', '1 visit', '2+ visits']
)

df['prior_emergency_group'].value_counts()

prior_emergency_group
0 visits     90383
1 visit       7677
2+ visits     3706
Name: count, dtype: int64

##### Analyze previous hospital visits

In [28]:
# Analyze previous hospital visits

# Select the visit columns
visit_columns = [
    'number_inpatient',
    'number_emergency',
    'number_outpatient'
]

# Calculate total previous visits for each row
df['total_previous_visits'] = df[visit_columns].sum(axis=1, min_count=1)

# Count the total_previous_visits values
df['total_previous_visits'].value_counts()

total_previous_visits
0     55828
1     19941
2     10062
3      5904
4      3570
5      2036
6      1313
7       868
8       554
9       430
10      270
11      248
12      136
13       98
15       97
14       87
16       68
17       63
18       32
19       32
20       23
22       15
21       14
27        9
24        9
25        7
26        6
35        5
36        5
29        5
23        4
30        4
31        2
38        2
28        2
32        2
42        2
33        2
37        2
68        2
49        1
34        1
40        1
48        1
80        1
61        1
41        1
Name: count, dtype: int64

In [29]:
# Creating a separate column

df['readmission_category'] = (
    df['readmitted']
    .map({
        'NO': 'No recorded readmission',
        '<30': 'Readmitted within 30 days',
        '>30': 'Readmitted after 30 days'
    })
)
df['readmission_category'].value_counts(dropna=False)

readmission_category
No recorded readmission      54864
Readmitted after 30 days     35545
Readmitted within 30 days    11357
Name: count, dtype: int64

In [30]:
# Calculate the distribution as percentages

category_percentage = (df['readmission_category'].value_counts(normalize=True, dropna=False).mul(100).round(2))
category_percentage

readmission_category
No recorded readmission      53.91
Readmitted after 30 days     34.93
Readmitted within 30 days    11.16
Name: proportion, dtype: float64

In [31]:
# Review all your new columns

new_columns = [
    'readmitted_30_days',
 'medication_changed',
 'length_of_stay_group',
 'prior_inpatient_group',
 'prior_emergency_group',
 'total_previous_visits',
 'readmission_category'
]

df[new_columns].head(10)

,readmitted_30_days,medication_changed,length_of_stay_group,prior_inpatient_group,prior_emergency_group,total_previous_visits,readmission_category
0,0,0,1-3 days,0 visits,0 visits,0,No recorded readmission
1,0,1,1-3 days,0 visits,0 visits,0,Readmitted after 30 days
2,0,0,1-3 days,1 visit,0 visits,3,No recorded readmission
3,0,1,1-3 days,0 visits,0 visits,0,No recorded readmission
4,0,1,1-3 days,0 visits,0 visits,0,No recorded readmission
5,0,0,1-3 days,0 visits,0 visits,0,Readmitted after 30 days
6,0,1,4-7 days,0 visits,0 visits,0,No recorded readmission
7,0,0,4-7 days,0 visits,0 visits,0,Readmitted after 30 days
8,0,1,8-14 days,0 visits,0 visits,0,No recorded readmission
9,0,1,8-14 days,0 visits,0 visits,0,No recorded readmission

In [32]:
df[new_columns].dtypes

readmitted_30_days          int64
medication_changed          Int64
length_of_stay_group     category
prior_inpatient_group    category
prior_emergency_group    category
total_previous_visits       int64
readmission_category          str
dtype: object

In [36]:
# Save analysis-ready dataset

df.to_csv('hospital_readmissions_analysis.csv', index=False)

In [34]:
df.columns.tolist()

['encounter_id',
 'patient_nbr',
 'race',
 'gender',
 'age',
 'weight',
 'admission_type_id',
 'discharge_disposition_id',
 'admission_source_id',
 'time_in_hospital',
 'payer_code',
 'medical_specialty',
 'num_lab_procedures',
 'num_procedures',
 'num_medications',
 'number_outpatient',
 'number_emergency',
 'number_inpatient',
 'diag_1',
 'diag_2',
 'diag_3',
 'number_diagnoses',
 'max_glu_serum',
 'A1Cresult',
 'metformin',
 'repaglinide',
 'nateglinide',
 'chlorpropamide',
 'glimepiride',
 'acetohexamide',
 'glipizide',
 'glyburide',
 'tolbutamide',
 'pioglitazone',
 'rosiglitazone',
 'acarbose',
 'miglitol',
 'troglitazone',
 'tolazamide',
 'examide',
 'citoglipton',
 'insulin',
 'glyburide-metformin',
 'glipizide-metformin',
 'glimepiride-pioglitazone',
 'metformin-rosiglitazone',
 'metformin-pioglitazone',
 'change',
 'diabetesMed',
 'readmitted',
 'readmitted_30_days',
 'medication_changed',
 'length_of_stay_group',
 'prior_inpatient_group',
 'prior_emergency_group',
 'total_previous_visits',
 'readmission_category']